# Generated by Django 3.2.13 on 2023-05-23 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': ('Рецепт в списке покупок',),
                'verbose_name_plural': 'Рецепты в списке покупок',
            },
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-id'], 'verbose_name': ('Избранный рецепт',), 'verbose_name_plural': ('Избранные рецепты',)},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': ('Ингредиент',), 'verbose_name_plural': ('Ингредиенты',)},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date'], 'verbose_name': ('Рецепт',), 'verbose_name_plural': ('Рецепты',)},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['ingredient'], 'verbose_name': ('Количество ингредиента',), 'verbose_name_plural': ('Количество ингредиентов',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': ('Тег',), 'verbose_name_plural': ('Теги',)},
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='user_favorite_unique',
        ),
        migrations.RemoveConstraint(
            model_name='ingredient',
            name='ingredient_name_unit_unique',
        ),
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_for_author',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_favourites', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
