# Generated by Django 3.2.13 on 2023-06-30 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20230630_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetag',
            old_name='tags',
            new_name='tag',
        ),
    ]
